import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from '../components/Sidebar'
const inter = Inter({ subsets: ["latin"] });
import Header from '../components/Header'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex bg-[rgb(247,251,255)] h-screen`}>
        {/* Sidebar here */}
        <Sidebar/>
        <main className="p-10 max-w-7xl w-full mx-auto">
          
          {/* Header here */}
          <Header/>
          {children}
          </main>
        </body>
    </html>
  );
}
